version: '3.9'

services:
  mysql:
    image: mysql:8.0.39
    container_name: nilroad-mysql
    ports:
      - ${MYSQL_LOCAL_PORT:-3306}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DATABASE_MYSQL_NAME:-sotoon}
      - MYSQL_USER=${DATABASE_MYSQL_USER:-sotoon}
      - MYSQL_PASSWORD=${DATABASE_MYSQL_PASSWORD:-sotoon}
    volumes:
      - mysql-data:/var/lib/mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: 'on-failure'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 15s
      timeout: 30s
      retries: 10

volumes:
  mysql-data: