name: PR Lint

on:
  pull_request:
    types: [ opened, edited, reopened, synchronize, ready_for_review ]
    branches: [ master ]

  workflow_dispatch:

jobs:
  pr-lint:
    name: Validate PR commit title meets commit convention
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: false
          validateSingleCommitMatchesPrTitle: true